services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./codebase:/var/www/html
    depends_on:
      - db_prod
    restart: always
    networks:
      - inft2201_network
  
  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    networks:
      - inft2201_network

  db_prod:
    image: postgres:18-bookworm
    container_name: postgres-prod
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init-prod:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - inft2201_network
    
networks:
  inft2201_network:
    driver: bridge
    name: inft2201_network